<?php

namespace QIT_CLI\Environment\Environments\Performance;

use QIT_CLI\Environment\Environments\EnvInfo;

class PerformanceEnvInfo extends EnvInfo {
	/** @var string */
	public $environment = 'performance';

	/** @var string The site URL, if any. */
	public $site_url;

	/** @var string */
	public $wp = '';

	/** @var bool */
	public $object_cache = false;

	/** @var string */
	public $php_version;

	/** @var string */
	public $nginx_port;

	/** @var string The slug of the extension under test. */
	public $sut_slug;

	/** @var string The type of the SUT, either "plugin" or "theme". */
	public $sut_type;

	/** @var string The entrypoint of the extension under test. */
	public $sut_entrypoint;

	/** @var string The path to the SUT on the host. */
	public $sut_path;

	/** @var int The Woo ID of the extension under test. */
	public $sut_id;

	/** @var string The domain being used. */
	public $domain;

	/** @var array<int,array{
	 *     slug:string,
	 *     test_tag:string,
	 *     type:string,
	 *     action:string,
	 *     path_in_php_container:string,
	 *     path_in_host:string,
	 *     version:string,
	 *     source:string,
	 *     id:int,
	 *     entrypoint:string,
	 *     requires:string,
	 *     tested:string,
	 *     activation_state:string,
	 *     activation_attempts:int,
	 *     activation_error:string,
	 *     activation_output:string,
	 *     activation_log:string,
	 *     activation_php_errors:array<string>,
	 *     activation_js_errors:array<string>,
	 *     activation_notices:array<string>,
	 *     activation_warnings:array<string>,
	 *     activation_debug:array<string>,
	 *     activation_query_errors:array<string>,
	 *     activation_time:int,
	 *     activation_memory:int,
	 *     activation_peak_memory:int,
	 *     activation_memory_limit:int,
	 *     activation_max_execution_time:int,
	 *     activation_max_input_time:int,
	 *     activation_max_input_vars:int,
	 *     activation_max_file_uploads:int,
	 *     activation_post_max_size:int,
	 *     activation_upload_max_filesize:int,
	 *     activation_max_input_nesting_level:int,
	 *     activation_max_input_depth:int,
	 *     activation_max_input_array_elements:int,
	 *     activation_max_input_string_length:int,
	 *     activation_max_input_time_override:int,
	 *     activation_max_execution_time_override:int,
	 *     activation_memory_limit_override:int,
	 *     activation_max_input_vars_override:int,
	 *     activation_max_file_uploads_override:int,
	 *     activation_post_max_size_override:int,
	 *     activation_upload_max_filesize_override:int,
	 *     activation_max_input_nesting_level_override:int,
	 *     activation_max_input_depth_override:int,
	 *     activation_max_input_array_elements_override:int,
	 *     activation_max_input_string_length_override:int,
	 *     activation_php_ini_path:string,
	 *     activation_php_ini_loaded:bool,
	 *     activation_php_ini_scanned:string,
	 *     activation_php_extensions:array<string>,
	 *     activation_php_modules:array<string>,
	 *     activation_php_functions:array<string>,
	 *     activation_php_classes:array<string>,
	 *     activation_php_constants:array<string>,
	 *     activation_php_superglobals:array<string>,
	 *     activation_php_error_reporting:int,
	 *     activation_php_display_errors:bool,
	 *     activation_php_display_startup_errors:bool,
	 *     activation_php_log_errors:bool,
	 *     activation_php_log_errors_max_len:int,
	 *     activation_php_ignore_repeated_errors:bool,
	 *     activation_php_ignore_repeated_source:bool,
	 *     activation_php_report_memleaks:bool,
	 *     activation_php_track_errors:bool,
	 *     activation_php_html_errors:bool,
	 *     activation_php_docref_root:string,
	 *     activation_php_docref_ext:string,
	 *     activation_php_error_prepend_string:string,
	 *     activation_php_error_append_string:string,
	 *     activation_php_error_log:string,
	 *     activation_php_syslog_facility:int,
	 *     activation_php_syslog_ident:string,
	 *     activation_php_syslog_filter:int,
	 *     activation_php_auto_prepend_file:string,
	 *     activation_php_auto_append_file:string,
	 *     activation_php_default_mimetype:string,
	 *     activation_php_default_charset:string,
	 *     activation_php_input_encoding:string,
	 *     activation_php_output_encoding:string,
	 *     activation_php_internal_encoding:string,
	 *     activation_php_regex_back_end:string,
	 *     activation_php_regex_default_match_limit:int,
	 *     activation_php_regex_default_recursion_limit:int,
	 *     activation_php_serialize_precision:int,
	 *     activation_php_serialize_format:string,
	 *     activation_php_zend_assertions:int,
	 *     activation_php_zend_signal_check:bool,
	 *     activation_php_zend_multibyte:bool,
	 *     activation_php_zend_script_encoding:string,
	 *     activation_php_zend_detect_unicode:bool,
	 *     activation_php_zend_enable_gc:bool,
	 *     activation_php_zend_gc_stats:bool,
	 *     activation_php_expose_php:bool,
	 *     activation_php_max_input_time:int,
	 *     activation_php_max_execution_time:int,
	 *     activation_php_max_input_vars:int,
	 *     activation_php_max_file_uploads:int,
	 *     activation_php_post_max_size:int,
	 *     activation_php_upload_max_filesize:int,
	 *     activation_php_max_input_nesting_level:int,
	 *     activation_php_max_input_depth:int,
	 *     activation_php_max_input_array_elements:int,
	 *     activation_php_max_input_string_length:int,
	 *     activation_php_arg_separator_output:string,
	 *     activation_php_arg_separator_input:string,
	 *     activation_php_variables_order:string,
	 *     activation_php_request_order:string,
	 *     activation_php_register_argc_argv:bool,
	 *     activation_php_auto_globals_jit:bool,
	 *     activation_php_short_open_tag:bool,
	 *     activation_php_precision:int,
	 *     activation_php_y2k_compliance:bool,
	 *     activation_php_output_buffering:int,
	 *     activation_php_output_handler:string,
	 *     activation_php_zlib_output_compression:bool,
	 *     activation_php_zlib_output_compression_level:int,
	 *     activation_php_zlib_output_handler:string,
	 *     activation_php_implicit_flush:bool,
	 *     activation_php_unserialize_callback_func:string,
	 *     activation_php_unserialize_max_depth:int,
	 *     activation_php_serialize_precision:int,
	 *     activation_php_open_basedir:string,
	 *     activation_php_disable_functions:string,
	 *     activation_php_disable_classes:string,
	 *     activation_php_realpath_cache_size:int,
	 *     activation_php_realpath_cache_ttl:int,
	 *     activation_php_zend_enable_gc:bool,
	 *     activation_php_zend_gc_stats:bool,
	 *     activation_php_include_path:string,
	 *     activation_php_doc_root:string,
	 *     activation_php_user_dir:string,
	 *     activation_php_user_ini_filename:string,
	 *     activation_php_user_ini_cache_ttl:int,
	 *     activation_php_extension_dir:string,
	 *     activation_php_sys_temp_dir:string,
	 *     activation_php_enable_dl:bool,
	 *     activation_php_cgi_force_redirect:bool,
	 *     activation_php_cgi_nph:bool,
	 *     activation_php_cgi_redirect_status_env:string,
	 *     activation_php_cgi_fix_pathinfo:bool,
	 *     activation_php_cgi_discard_path:bool,
	 *     activation_php_fastcgi_impersonate:bool,
	 *     activation_php_fastcgi_logging:bool,
	 *     activation_php_cgi_rfc2616_headers:bool,
	 *     activation_php_cgi_check_shebang_line:bool,
	 *     activation_php_file_uploads:bool,
	 *     activation_php_upload_tmp_dir:string,
	 *     activation_php_upload_max_filesize:int,
	 *     activation_php_max_file_uploads:int,
	 *     activation_php_allow_url_fopen:bool,
	 *     activation_php_allow_url_include:bool,
	 *     activation_php_user_agent:string,
	 *     activation_php_default_socket_timeout:int,
	 *     activation_php_http_context:string,
	 *     activation_php_auto_detect_line_endings:bool,
	 *     activation_php_date_default_timezone:string,
	 *     activation_php_date_default_latitude:float,
	 *     activation_php_date_default_longitude:float,
	 *     activation_php_date_sunrise_zenith:float,
	 *     activation_php_date_sunset_zenith:float,
	 *     activation_php_filter_default:string,
	 *     activation_php_filter_default_flags:int,
	 *     activation_php_iconv_input_encoding:string,
	 *     activation_php_iconv_internal_encoding:string,
	 *     activation_php_iconv_output_encoding:string,
	 *     activation_php_intl_default_locale:string,
	 *     activation_php_intl_error_level:int,
	 *     activation_php_intl_use_exceptions:bool,
	 *     activation_php_sqlite3_extension_dir:string,
	 *     activation_php_sqlite3_defensive:bool,
	 *     activation_php_pcre_backtrack_limit:int,
	 *     activation_php_pcre_recursion_limit:int,
	 *     activation_php_pcre_jit:bool,
	 *     activation_php_pdo_odbc_connection_pooling:bool,
	 *     activation_php_pdo_odbc_db2_instance_name:string,
	 *     activation_php_phar_readonly:bool,
	 *     activation_php_phar_require_hash:bool,
	 *     activation_php_phar_cache_list:string,
	 *     activation_php_session_save_handler:string,
	 *     activation_php_session_save_path:string,
	 *     activation_php_session_use_strict_mode:bool,
	 *     activation_php_session_use_cookies:bool,
	 *     activation_php_session_use_only_cookies:bool,
	 *     activation_php_session_name:string,
	 *     activation_php_session_auto_start:bool,
	 *     activation_php_session_cookie_lifetime:int,
	 *     activation_php_session_cookie_path:string,
	 *     activation_php_session_cookie_domain:string,
	 *     activation_php_session_cookie_secure:bool,
	 *     activation_php_session_cookie_httponly:bool,
	 *     activation_php_session_cookie_samesite:string,
	 *     activation_php_session_serialize_handler:string,
	 *     activation_php_session_gc_probability:int,
	 *     activation_php_session_gc_divisor:int,
	 *     activation_php_session_gc_maxlifetime:int,
	 *     activation_php_session_referer_check:string,
	 *     activation_php_session_entropy_length:int,
	 *     activation_php_session_entropy_file:string,
	 *     activation_php_session_cache_limiter:string,
	 *     activation_php_session_cache_expire:int,
	 *     activation_php_session_use_trans_sid:bool,
	 *     activation_php_session_trans_sid_tags:string,
	 *     activation_php_session_trans_sid_hosts:string,
	 *     activation_php_session_bug_compat_42:bool,
	 *     activation_php_session_bug_compat_warn:bool,
	 *     activation_php_session_hash_function:int,
	 *     activation_php_session_hash_bits_per_character:int,
	 *     activation_php_session_upload_progress_enabled:bool,
	 *     activation_php_session_upload_progress_cleanup:bool,
	 *     activation_php_session_upload_progress_prefix:string,
	 *     activation_php_session_upload_progress_name:string,
	 *     activation_php_session_upload_progress_freq:string,
	 *     activation_php_session_upload_progress_min_freq:int,
	 *     activation_php_session_lazy_write:bool,
	 *     activation_php_assert_active:bool,
	 *     activation_php_assert_warning:bool,
	 *     activation_php_assert_bail:bool,
	 *     activation_php_assert_quiet_eval:bool,
	 *     activation_php_assert_callback:string,
	 *     activation_php_com_typelib_file:string,
	 *     activation_php_com_allow_dcom:bool,
	 *     activation_php_com_autoregister_typelib:bool,
	 *     activation_php_com_autoregister_casesensitive:bool,
	 *     activation_php_com_autoregister_verbose:bool,
	 *     activation_php_com_code_page:int,
	 *     activation_php_com_dotnet_version:string,
	 *     activation_php_mbstring_language:string,
	 *     activation_php_mbstring_detect_order:string,
	 *     activation_php_mbstring_http_input:string,
	 *     activation_php_mbstring_http_output:string,
	 *     activation_php_mbstring_internal_encoding:string,
	 *     activation_php_mbstring_script_encoding:string,
	 *     activation_php_mbstring_substitute_character:string,
	 *     activation_php_mbstring_func_overload:int,
	 *     activation_php_mbstring_encoding_translation:bool,
	 *     activation_php_mbstring_strict_detection:bool,
	 *     activation_php_exif_encode_unicode:string,
	 *     activation_php_exif_decode_unicode_motorola:string,
	 *     activation_php_exif_decode_unicode_intel:string,
	 *     activation_php_exif_encode_jis:string,
	 *     activation_php_exif_decode_jis_motorola:string,
	 *     activation_php_exif_decode_jis_intel:string,
	 *     activation_php_tidy_default_config:string,
	 *     activation_php_tidy_clean_output:bool,
	 *     activation_php_soap_wsdl_cache_enabled:bool,
	 *     activation_php_soap_wsdl_cache_dir:string,
	 *     activation_php_soap_wsdl_cache_ttl:int,
	 *     activation_php_soap_wsdl_cache_limit:int,
	 *     activation_php_ldap_max_links:int,
	 *     activation_php_dba_default_handler:string,
	 *     activation_php_mysqlnd_collect_statistics:bool,
	 *     activation_php_mysqlnd_collect_memory_statistics:bool,
	 *     activation_php_mysqlnd_debug:string,
	 *     activation_php_mysqlnd_log_mask:int,
	 *     activation_php_mysqlnd_mempool_default_size:int,
	 *     activation_php_mysqlnd_net_cmd_buffer_size:int,
	 *     activation_php_mysqlnd_net_read_buffer_size:int,
	 *     activation_php_mysqlnd_net_read_timeout:int,
	 *     activation_php_mysqlnd_sha256_server_public_key:string,
	 *     activation_php_oci8_max_persistent:int,
	 *     activation_php_oci8_persistent_timeout:int,
	 *     activation_php_oci8_ping_interval:int,
	 *     activation_php_oci8_connection_class:string,
	 *     activation_php_oci8_events:bool,
	 *     activation_php_oci8_statement_cache_size:int,
	 *     activation_php_oci8_default_prefetch:int,
	 *     activation_php_oci8_old_oci_close_semantics:bool,
	 *     activation_php_oci8_privileged_connect:bool,
	 *     activation_php_odbc_allow_persistent:bool,
	 *     activation_php_odbc_check_persistent:bool,
	 *     activation_php_odbc_max_persistent:int,
	 *     activation_php_odbc_max_links:int,
	 *     activation_php_odbc_defaultlrl:int,
	 *     activation_php_odbc_defaultbinmode:int,
	 *     activation_php_ibase_allow_persistent:bool,
	 *     activation_php_ibase_max_persistent:int,
	 *     activation_php_ibase_max_links:int,
	 *     activation_php_ibase_default_db:string,
	 *     activation_php_ibase_default_user:string,
	 *     activation_php_ibase_default_password:string,
	 *     activation_php_ibase_default_charset:string,
	 *     activation_php_ibase_timestampformat:string,
	 *     activation_php_ibase_dateformat:string,
	 *     activation_php_ibase_timeformat:string,
	 *     activation_php_mysql_allow_local_infile:bool,
	 *     activation_php_mysql_allow_persistent:bool,
	 *     activation_php_mysql_cache_size:int,
	 *     activation_php_mysql_max_persistent:int,
	 *     activation_php_mysql_max_links:int,
	 *     activation_php_mysql_default_port:int,
	 *     activation_php_mysql_default_socket:string,
	 *     activation_php_mysql_default_host:string,
	 *     activation_php_mysql_default_user:string,
	 *     activation_php_mysql_default_password:string,
	 *     activation_php_mysql_connect_timeout:int,
	 *     activation_php_mysql_trace_mode:bool,
	 *     activation_php_mysqli_max_persistent:int,
	 *     activation_php_mysqli_allow_persistent:bool,
	 *     activation_php_mysqli_max_links:int,
	 *     activation_php_mysqli_cache_size:int,
	 *     activation_php_mysqli_default_port:int,
	 *     activation_php_mysqli_default_socket:string,
	 *     activation_php_mysqli_default_host:string,
	 *     activation_php_mysqli_default_user:string,
	 *     activation_php_mysqli_default_pw:string,
	 *     activation_php_mysqli_reconnect:bool,
	 *     activation_php_mysqli_rollback_on_cached_plink:bool,
	 *     activation_php_pgsql_allow_persistent:bool,
	 *     activation_php_pgsql_auto_reset_persistent:bool,
	 *     activation_php_pgsql_max_persistent:int,
	 *     activation_php_pgsql_max_links:int,
	 *     activation_php_pgsql_ignore_notice:bool,
	 *     activation_php_pgsql_log_notice:bool,
	 *     activation_php_bcmath_scale:int,
	 *     activation_php_browscap:string,
	 *     activation_php_ifx_default_host:string,
	 *     activation_php_ifx_default_user:string,
	 *     activation_php_ifx_default_password:string,
	 *     activation_php_ifx_allow_persistent:bool,
	 *     activation_php_ifx_max_persistent:int,
	 *     activation_php_ifx_max_links:int,
	 *     activation_php_ifx_textasvarchar:bool,
	 *     activation_php_ifx_byteasvarchar:bool,
	 *     activation_php_ifx_charasvarchar:bool,
	 *     activation_php_ifx_blobinfile:bool,
	 *     activation_php_ifx_nullformat:bool,
	 *     activation_php_sybase_allow_persistent:bool,
	 *     activation_php_sybase_max_persistent:int,
	 *     activation_php_sybase_max_links:int,
	 *     activation_php_sybase_min_error_severity:int,
	 *     activation_php_sybase_min_message_severity:int,
	 *     activation_php_sybase_compatability_mode:bool,
	 *     activation_php_sybct_allow_persistent:bool,
	 *     activation_php_sybct_max_persistent:int,
	 *     activation_php_sybct_max_links:int,
	 *     activation_php_sybct_min_server_severity:int,
	 *     activation_php_sybct_min_client_severity:int,
	 *     activation_php_sybct_login_timeout:int,
	 *     activation_php_sybct_timeout:int,
	 *     activation_php_sybct_packet_size:int,
	 *     activation_php_sybct_hostname:string,
	 *     activation_php_sybct_deadlock_retry_count:int,
	 *     activation_php_dbx_colnames_case:string,
	 *     activation_php_ingres_allow_persistent:bool,
	 *     activation_php_ingres_max_persistent:int,
	 *     activation_php_ingres_max_links:int,
	 *     activation_php_ingres_default_database:string,
	 *     activation_php_ingres_default_user:string,
	 *     activation_php_ingres_default_password:string,
	 *     activation_php_ingres_report_db_warnings:bool,
	 *     activation_php_ingres_cursor_mode:int,
	 *     activation_php_ingres_blob_segment_length:int,
	 *     activation_php_ingres_trace_connect:bool,
	 *     activation_php_ingres_timeout:int,
	 *     activation_php_ingres_array_index_start:int,
	 *     activation_php_ingres_auto_multi:bool,
	 *     activation_php_ingres_default_cursor_concurrency:int,
	 *     activation_php_ingres_describe_decimal:bool,
	 *     activation_php_ingres_utf8:bool,
	 *     activation_php_msql_allow_persistent:bool,
	 *     activation_php_msql_max_persistent:int,
	 *     activation_php_msql_max_links:int,
	 *     activation_php_mssql_allow_persistent:bool,
	 *     activation_php_mssql_max_persistent:int,
	 *     activation_php_mssql_max_links:int,
	 *     activation_php_mssql_min_error_severity:int,
	 *     activation_php_mssql_min_message_severity:int,
	 *     activation_php_mssql_compatability_mode:bool,
	 *     activation_php_mssql_connect_timeout:int,
	 *     activation_php_mssql_timeout:int,
	 *     activation_php_mssql_textlimit:int,
	 *     activation_php_mssql_textsize:int,
	 *     activation_php_mssql_batchsize:int,
	 *     activation_php_mssql_datetimeconvert:bool,
	 *     activation_php_mssql_secure_connection:bool,
	 *     activation_php_mssql_max_procs:int,
	 *     activation_php_mssql_charset:string,
	 *     activation_php_uodbc_allow_persistent:bool,
	 *     activation_php_uodbc_check_persistent:bool,
	 *     activation_php_uodbc_max_persistent:int,
	 *     activation_php_uodbc_max_links:int,
	 *     activation_php_uodbc_defaultlrl:int,
	 *     activation_php_uodbc_defaultbinmode:int,
	 *     activation_php_uodbc_default_db:string,
	 *     activation_php_uodbc_default_user:string,
	 *     activation_php_uodbc_default_pw:string,
	 *     activation_php_uodbc_default_cursortype:int,
	 *     activation_php_xml_parser_type:string,
	 *     activation_php_wddx_serialize_vars:bool,
	 *     activation_php_xsl_extension_dir:string,
	 *     activation_php_xsl_xsltproc_debug:bool,
	 *     activation_php_xsl_security_prefs:int,
	 *     activation_php_xsl_max_depth:int,
	 *   }> $plugins */
	public $plugins = [];

	/** @var array<int,array{
	 *     slug:string,
	 *     test_tag:string,
	 *     type:string,
	 *     action:string,
	 *     path_in_php_container:string,
	 *     path_in_host:string,
	 *     version:string,
	 *     source:string,
	 *     id:int,
	 *     entrypoint:string,
	 *     requires:string,
	 *     tested:string,
	 *     activation_state:string,
	 *   }> $themes */
	public $themes = [];

	/** @var array k6 configuration overrides */
	public $k6_config = [];

	/** @var string Docker network name */
	public $docker_network;

	/** @var string Environment ID */
	public $env_id;

	/** @var string Temporary environment directory */
	public $temporary_env;

	/** @var string Action to perform on the SUT */
	public $sut_action;

	/** @var string WooCommerce version */
	public $woo_version;

	/** @var array PHP extensions to enable */
	public $php_extensions = [];

	/** @var string The k6 test tag to be executed */
	public $k6_test_tag = '';
}