/**
 * Anonymous capability discovery via named actions.
 *
 * Like WordPress do_action() — multiple packages can register implementations
 * for the same action name. Consumers iterate over all registered actions.
 *
 * Reads the actions manifest (generated by QIT CLI) and lazily loads
 * action modules. Each action is the `export default` from a file,
 * with `.provider` metadata attached (which package registered it).
 *
 * Always available: returns [] if no manifest is set.
 */

import { readFileSync } from 'fs';
import { createRequire } from 'module';

/** An action function with metadata about which package registered it. */
export interface ActionFunction {
  /** The function itself (callable). */
  (...args: any[]): any;
  /** Package identifier that registered this action, e.g. 'stripe/payments'. */
  provider: string;
}

interface ManifestEntry {
  provider: string;
  path: string;
}

type Manifest = Record<string, ManifestEntry[]>;

let _cache: Map<string, ActionFunction[]> | null = null;

const _require = createRequire(import.meta.url);

function loadManifest(): Map<string, ActionFunction[]> {
  if (_cache) return _cache;

  _cache = new Map();

  const manifestPath = process.env.QIT_ACTIONS_MANIFEST;
  if (!manifestPath) {
    return _cache;
  }

  let manifest: Manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    return _cache;
  }

  for (const [name, entries] of Object.entries(manifest)) {
    const fns: ActionFunction[] = [];

    for (const entry of entries) {
      const mod = _require(entry.path);
      const fn = (mod.default ?? mod) as ActionFunction;

      // Attach metadata directly to the function object.
      fn.provider = entry.provider;

      fns.push(fn);
    }

    _cache.set(name, fns);
  }

  return _cache;
}

/**
 * Get all registered actions for a named capability.
 *
 * Returns [] if no actions are registered for the given name.
 * This is by design: zero actions = zero test cases, not an error.
 */
export function actions(name: string): ActionFunction[] {
  return loadManifest().get(name) ?? [];
}

/**
 * Check whether at least one action is registered for a capability.
 */
export function hasAction(name: string): boolean {
  return actions(name).length > 0;
}
