/**
 * Known dependency access.
 *
 * Reads the package map (generated by QIT CLI) and lazily require()s
 * each package's entry point. Returns whatever the package exports.
 *
 * Always available: throws if the requested package is not in the map.
 */

import { readFileSync } from 'fs';
import { createRequire } from 'module';

type PackageMap = Record<string, string>;

let _map: PackageMap | null = null;
const _packageCache = new Map<string, Record<string, any>>();

const _require = createRequire(import.meta.url);

function getMap(): PackageMap {
  if (_map) return _map;

  const mapPath = process.env.QIT_PACKAGE_MAP;
  if (!mapPath) {
    _map = {};
    return _map;
  }

  try {
    _map = JSON.parse(readFileSync(mapPath, 'utf-8'));
  } catch {
    _map = {};
  }

  return _map!;
}

/**
 * Load a test/utility package's exports by name.
 *
 * Uses standard Node.js module resolution on the package's directory
 * (resolves via package.json main/exports or index.ts convention).
 *
 * @param name - Package identifier, e.g. 'woocommerce/core-utils'.
 * @returns The package's module exports.
 * @throws If the package is not in the current environment's package map.
 */
export function loadPackage(name: string): Record<string, any> {
  const cached = _packageCache.get(name);
  if (cached) return cached;

  const map = getMap();
  const packagePath = map[name];

  if (!packagePath) {
    const available = Object.keys(map);
    const availableStr = available.length > 0
      ? `Available packages: ${available.join(', ')}`
      : 'No packages are loaded in this environment.';

    throw new Error(
      `Package '${name}' is not available.\n` +
      `${availableStr}\n` +
      `Make sure it is included via --test-package ${name}`
    );
  }

  const mod = _require(packagePath);
  _packageCache.set(name, mod);
  return mod;
}
