/**
 * Anonymous capability discovery.
 *
 * Reads the providers manifest (generated by QIT CLI) and lazily loads
 * provider modules. Each provider is the `export default` from a file,
 * with `.provider` metadata attached.
 *
 * Always available: returns [] if no manifest is set.
 */

import { readFileSync } from 'fs';
import { createRequire } from 'module';

/** Metadata attached to every provider function. */
export interface ProviderFunction {
  /** The function itself (callable). */
  (...args: any[]): any;
  /** Package identifier, e.g. 'stripe/payments'. */
  provider: string;
}

interface ManifestEntry {
  provider: string;
  path: string;
}

type Manifest = Record<string, ManifestEntry[]>;

let _cache: Map<string, ProviderFunction[]> | null = null;

const _require = createRequire(import.meta.url);

function loadManifest(): Map<string, ProviderFunction[]> {
  if (_cache) return _cache;

  _cache = new Map();

  const manifestPath = process.env.QIT_PROVIDERS_MANIFEST;
  if (!manifestPath) {
    return _cache;
  }

  let manifest: Manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    return _cache;
  }

  for (const [name, entries] of Object.entries(manifest)) {
    const fns: ProviderFunction[] = [];

    for (const entry of entries) {
      const mod = _require(entry.path);
      const fn = (mod.default ?? mod) as ProviderFunction;

      // Attach metadata directly to the function object.
      fn.provider = entry.provider;

      fns.push(fn);
    }

    _cache.set(name, fns);
  }

  return _cache;
}

/**
 * Get all providers of a named capability.
 *
 * Returns [] if no providers are loaded for the given name.
 * This is by design: zero providers = zero test cases, not an error.
 */
export function providers(name: string): ProviderFunction[] {
  return loadManifest().get(name) ?? [];
}

/**
 * Check whether at least one provider exists for a capability.
 */
export function hasProvider(name: string): boolean {
  return providers(name).length > 0;
}
