name: QIT CLI Code tests
on:
  pull_request:
    paths:
      - 'src/**.php'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: code-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Docker Cache (default PHP 8.3)
        uses: ./.github/actions/restore-docker-cache
        with:
          php-version: "8.3"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        id: cache-composer
        with:
          path: src/vendor
          key: ${{ runner.os }}-${{ hashFiles('src/composer.lock') }}

      - name: Composer install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        working-directory: src
        run: composer install

      - name: Run PHPCS
        run: make phpcs

      - name: Run PHPStan
        run: make phpstan

      - name: Run Phan
        run: make phan
