name: Phan Tests
on:
  pull_request:
    paths:
      - 'src/**.php'

jobs:
  phan_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Bogus
        run: echo "Bogus workflow to allow PR-based testing."
