name: Phan Tests
on:
  pull_request:
    paths:
      - 'src/**.php'
  workflow_dispatch:

concurrency:
  group: phan-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  restore_docker_cache:
    uses: ./.github/workflows/restore-docker-cache.yml
    with:
      php-version: ${{ matrix.php }}

  phan_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    needs: restore_docker_cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v3
        id: cache-composer
        with:
          path: src/vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('src/composer.lock') }}

      - name: Composer install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: |
          cd src
          composer install --no-interaction --no-suggest --prefer-dist

      - name: Run Phan
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: make phan
