name: Publish @woocommerce/qit-runtime

on:
  push:
    branches: [trunk]
    paths: ['packages/qit-runtime/**']

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Ensure npm supports OIDC
        run: npm install -g npm@latest

      - name: Install, test, build
        working-directory: packages/qit-runtime
        run: npm ci && npm test && npm run build

      - name: Publish
        working-directory: packages/qit-runtime
        run: npm publish --access public --provenance
