name: QIT Self-Tests - PHPStan

on:
  # Every day at 11:07am and 11:07pm UTC
  schedule:
    - cron: '7 11 * * *'
    - cron: '7 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  phpstan_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: phpstan
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}