name: QIT Windows

on:
  push:
    branches:
      - trunk
  # Manually
  workflow_dispatch:

jobs:
  qit_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]
    env:
      NO_COLOR: 1
      QIT_DISABLE_ONBOARDING: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, zip
          coverage: none

      - name: Composer install
        working-directory: src
        run: composer install

      - name: Enable dev mode
        working-directory: src
        run: php qit-cli.php dev

      - name: Run SSL connection without CA file
        working-directory: src
        env:
          OPENSSL_CONF: ''
        run: |
          php -d openssl.cafile='' -d curl.cainfo='' qit-cli.php sync -vvv
          if ($LASTEXITCODE -eq 0) {
            Write-Host "Test passed: SSL connection succeeded"
          } else {
            Write-Host "Test failed: SSL connection did not succeed"
            exit 1
          }