name: QIT Self-Tests - E2E

on:
  # Every day at 11:05am and 11:05pm UTC
  schedule:
    - cron: '5 11 * * *'
    - cron: '5 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  e2e_tests:
    if: github.event_name != 'push'
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: e2e
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}