name: QIT Self-Tests - Security

on:
  # Every day at 11am and 11pm UTC (6am and 6pm ET)
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  security_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: security
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}
      QIT_STAGING_SECRET: ${{ secrets.QIT_STAGING_SECRET }}