name: QIT Orchestration Tests

on:
  # Every day at 11pm UTC (6pm ET)
  schedule:
    - cron: '0 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  orchestration-tests:
    runs-on: ubuntu-latest
    env:
      NO_COLOR: 1
      QIT_DISABLE_ONBOARDING: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Enable dev mode
        run: ./qit dev

      - name: Connect to Staging QIT
        run: ./qit backend:add --environment="staging" --qit_secret="${{ secrets.QIT_STAGING_SECRET }}" --manager_url="https://stagingcompatibilitydashboard.wpcomstaging.com"

      - name: Composer install
        working-directory: src
        run: composer install

      - name: Run Orchestration Tests
        env:
          QIT_SELF_TESTS: 1
        run: |
          cd _tests/orchestration
          php ../../src/qit-cli.php run:e2e woocommerce-amazon-s3-storage -v

      - name: Get Report Path
        if: ${{ !cancelled() }}
        working-directory: src
        run: |
          echo "REPORT_PATH=$(php qit-cli.php e2e-report --dir_only)" >> $GITHUB_ENV

      - name: Upload Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: orchestration-test-report
          path: ${{ env.REPORT_PATH }}
          retention-days: 7