name: QIT Self-Tests - API

on:
  # Every day at 11:03am and 11:03pm UTC
  schedule:
    - cron: '3 11 * * *'
    - cron: '3 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  api_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: api
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}