name: QIT Environment Test - Linux

on:
  # Manually
  workflow_dispatch:

jobs:
    environment_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]
    env:
      NO_COLOR: 1
      QIT_DISABLE_ONBOARDING: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
          coverage: none

      - name: Run SSL connection without CA file fallback Test
        working-directory: src
        env:
          OPENSSL_CONF: ''
        run: |
          php -d openssl.cafile='' -d curl.cainfo='' qit-cli.php sync
          if [ $? -ne 0 ]; then
            echo "Test passed: SSL connection failed as expected"
          else
            echo "Test failed: SSL connection did not fail as expected"
            exit 1
          fi

      - name: Run SSL connection with CA file fallback Test
        working-directory: src
        env:
          QIT_WINDOWS_DOWNLOAD_CA: yes
          OPENSSL_CONF: ''
        run: |
          php -d openssl.cafile='' -d curl.cainfo='' qit-cli.php sync
          if [ $? -eq 0 ]; then
            echo "Test passed: SSL connection succeeded"
          else
            echo "Test failed: SSL connection did not succeed"
            exit 1
          fi

