name: QIT Self-Tests - Security

on:
  # Every day at 11:09am and 11:09pm UTC
  schedule:
    - cron: '9 11 * * *'
    - cron: '9 23 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  security_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: security
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}